/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsDathuc;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuans
 */
public class App extends javax.swing.JFrame {

    private Dathuc du, dathuc1, dathuc2, ketqua;
    private int bac;
    private float x;
    private String txtLoai;
    private List<History> history;
    private int loai;//0=chia,1=nhan,2=cong,3=tru,4=dao ham

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        history = new ArrayList<History>();
        dathuc1 = new Dathuc();
        dathuc2 = new Dathuc();
        ketqua = new Dathuc();
        du = new Dathuc();
        bac = 1;
        x = 1;
        btnTinh.setEnabled(false);
        txtDathuc1.setEnabled(false);
        txtDathuc2.setEnabled(false);

    }

    public void themLichsu(String dathuc1, String dathuc2, String ketqua, int loai) {
        String txtloai = new String();
        history.add(0, new History(dathuc1, dathuc2, ketqua, loai));
        Vector tieude = new Vector();
        tieude.add("Thời gian");
        tieude.add("Kết quả");
        tieude.add("Loại");
        Vector noidung = new Vector();
        for (int i = 0; i < history.size(); i++) {
            Vector dong = new Vector();
            dong.add(history.get(i).layThoigian());
            dong.add(new String(history.get(i).layKetqua().replaceAll("'", " dư ")));
            switch (history.get(i).layLoai()) {
                case -1:

// code block
                    break;
                case 0:
                    txtloai = "Chia";
                    break;
                case 1:
                    txtloai = "Nhân";
                    // code block
                    break;
                case 2:
                    txtloai = "Cộng";
                    // code block
                    break;
                case 3:
                    txtloai = "Trừ";
                    // code block
                    break;
                case 4:
                    txtloai = "Đạo hàm";
                    // code block
                    break;
                case 5:
                    txtloai = "Giá trị";
                    // code block
                    break;
            }
            dong.add(txtloai);
            noidung.add(dong);
        }
        tableLichsu.setModel(new DefaultTableModel(noidung, tieude));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputPanel = new javax.swing.JPanel();
        btnDaoham = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        txtDathuc1 = new javax.swing.JTextField();
        txtDathuc2 = new javax.swing.JTextField();
        lbldathuc2 = new javax.swing.JLabel();
        lbldathuc1 = new javax.swing.JLabel();
        btnTinh = new javax.swing.JButton();
        lblLoai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Btntinhgiatri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLichsu = new javax.swing.JTable();
        btnDocFile = new javax.swing.JButton();
        btnXuatfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        btnDaoham.setText("Đạo hàm");
        btnDaoham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaohamActionPerformed(evt);
            }
        });

        btnNhan.setText("Nhân");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });

        btnTru.setText("Trừ");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        btnCong.setText("Cộng");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnChia.setText("Chia");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setMaximumSize(new java.awt.Dimension(443, 299));

        txtDathuc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDathuc2ActionPerformed(evt);
            }
        });

        lbldathuc2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldathuc2.setText("Đa thức 2:");

        lbldathuc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldathuc1.setText("Đa thức 1:");

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDathuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldathuc1)
                    .addComponent(txtDathuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldathuc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbldathuc1)
                .addGap(12, 12, 12)
                .addComponent(txtDathuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldathuc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDathuc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );

        lblLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoai.setText("Bảng nhập");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Chú ý:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Định dạng là (số)x(mũ) hoặc (số)x^(mũ)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ví dụ: 1+3x3 hoặc 2x^4 +4 hoặc x+4x^4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        Btntinhgiatri.setText("Tính giá trị");
        Btntinhgiatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntinhgiatriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCong, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(btnChia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnDaoham, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Btntinhgiatri)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnNhan)
                    .addComponent(btnDaoham))
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTru)
                    .addComponent(btnChia)
                    .addComponent(Btntinhgiatri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        tableLichsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Thời gian", "Kết quả", "Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLichsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLichsuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLichsu);
        if (tableLichsu.getColumnModel().getColumnCount() > 0) {
            tableLichsu.getColumnModel().getColumn(0).setResizable(false);
            tableLichsu.getColumnModel().getColumn(1).setResizable(false);
            tableLichsu.getColumnModel().getColumn(2).setResizable(false);
        }

        btnDocFile.setText("Thực hiện phép tính từ file");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnXuatfile.setText("Xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnDocFile)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableLichsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLichsuMouseClicked
        int sodong = tableLichsu.getSelectedRow();
        btnTinh.setEnabled(true);
        txtDathuc1.setText(history.get(sodong).layDathuc1());
        txtDathuc2.setText(history.get(sodong).layDathuc2());
        loai = history.get(sodong).layLoai();
        switch (loai) {
            case 0:
                txtLoai = "Chia đa thức";
                break;
            case 1:
                txtLoai = "Nhân đa thức";
                break;
            case 2:
                txtLoai = "Cộng đa thức";
                break;
            case 3:
                txtLoai = "Trừ đa thức";
                break;
            case 4:
                txtLoai = "Đạo hàm đa thức";
                lbldathuc2.setText("bậc đạo hàm(mặc định là 1)");
                break;
            case 5:
                txtLoai = "Tính đa thức";
                lbldathuc2.setText("giá trị tại x là:");
                break;
        }
        lblLoai.setText(txtLoai);
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_tableLichsuMouseClicked

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        JFileChooser Cuasochon = new JFileChooser();
        Cuasochon.setApproveButtonText("Lưu");
        Cuasochon.showOpenDialog(this);
        File file = Cuasochon.getSelectedFile();
        history.forEach(his -> {
            his.luuvaoFile(file.getPath());
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        try {
            switch (loai) {
                case 0:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.dathuc2 = new Dathuc(txtDathuc2.getText());
                    this.ketqua = dathuc1.chiaDathuc(dathuc2)[0];
                    this.du = dathuc1.chiaDathuc(dathuc2)[1];
                    break;
                case 1:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.dathuc2 = new Dathuc(txtDathuc2.getText());
                    this.ketqua = dathuc1.nhandDathuc(dathuc2);
                    break;
                case 2:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.dathuc2 = new Dathuc(txtDathuc2.getText());
                    this.ketqua = dathuc1.CongDathuc(dathuc2);
                    break;
                case 3:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.dathuc2 = new Dathuc(txtDathuc2.getText());
                    this.ketqua = dathuc1.truDathuc(dathuc2);
                    break;
                case 4:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.bac = Integer.parseInt(txtDathuc2.getText());
                    this.ketqua = dathuc1.daohamDathuc(bac);
                    break;
                case 5:
                    this.dathuc1 = new Dathuc(txtDathuc1.getText());
                    this.ketqua = dathuc1.Tinhgiatri(Float.parseFloat(txtDathuc2.getText()));
                    break;
                default:
                    break;
            }

            if (loai == 0) {
                themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString() + "'" + du.toString(), loai);
            } else {
                themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString(), loai);
            }
            datlai();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nhập vào sai định dạng", "Lỗi định dạng", 1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTinhActionPerformed

    private void txtDathuc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDathuc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDathuc2ActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        loai = 2;
        btnTinh.setEnabled(true);
        lblLoai.setText("Cộng đa thức");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        loai = 3;
        btnTinh.setEnabled(true);
        lblLoai.setText("Trừ đa thức");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        loai = 1;
        btnTinh.setEnabled(true);
        lblLoai.setText("Nhân đa thức");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnDaohamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaohamActionPerformed
        loai = 4;
        btnTinh.setEnabled(true);
        lblLoai.setText("Đạo hàm đa thức");
        lbldathuc2.setText("bậc đạo hàm(mặc định là 1)");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);

    }//GEN-LAST:event_btnDaohamActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        JFileChooser Cuasochon = new JFileChooser();
        Cuasochon.setApproveButtonText("Lưu");
        Cuasochon.showOpenDialog(this);
        File file = Cuasochon.getSelectedFile();
        docFile(file.getPath());

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        loai = 0;
        btnTinh.setEnabled(true);
        lblLoai.setText("Chia đa thức");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiaActionPerformed

    private void BtntinhgiatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntinhgiatriActionPerformed
        loai = 5;
        btnTinh.setEnabled(true);
        lblLoai.setText("Tính đa thức");
        lbldathuc2.setText("giá trị tại x là:");
        txtDathuc1.setEnabled(true);
        txtDathuc2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtntinhgiatriActionPerformed
    private void datlai() {
        txtDathuc1.setText("");
        txtDathuc2.setText("");
        lblLoai.setText("Bảng nhập");
        txtDathuc1.setEnabled(false);
        txtDathuc2.setEnabled(false);
        btnTinh.setEnabled(false);
    }

    public List<History> docFilehistory(String duongdan) {
        FileReader fr = null;
        BufferedReader br = null;
        int bacdaoham = 1;
        Dathuc dathuc1, dathuc2, ketqua, du;
        dathuc1 = new Dathuc();
        dathuc2 = new Dathuc();
        ketqua = new Dathuc();
        du = new Dathuc();

        try {
            fr = new FileReader(duongdan);
            br = new BufferedReader(fr);

            String dong;
            String[] ptdong;
            while ((dong = br.readLine()) != null) {
                ptdong = dong.split("'");

                switch (Integer.parseInt(ptdong[0])) {
                    case 0:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.chiaDathuc(dathuc2)[0];
                        break;
                    case 1:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.nhandDathuc(dathuc2);
                        break;
                    case 2:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.CongDathuc(dathuc2);
                        break;
                    case 3:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.truDathuc(dathuc2);
                        break;
                    case 4:
                        dathuc1 = new Dathuc(ptdong[1]);
                        bacdaoham = Integer.parseInt(ptdong[2]);
                        ketqua = dathuc1.daohamDathuc(bacdaoham);
                        break;
                    case 5:
                        dathuc1 = new Dathuc(ptdong[1]);
                        x = Float.parseFloat(ptdong[2]);
                        ketqua = dathuc1.Tinhgiatri(x);
                        break;
                    default:
                        break;
                }
                switch (Integer.parseInt(ptdong[0])) {
                    case 0:
                        themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString() + "'" + du.toString(), Integer.parseInt(ptdong[0]));
                        break;
                    case 4:
                        themLichsu(dathuc1.toString(), Integer.toString(bacdaoham), ketqua.toString(), Integer.parseInt(ptdong[0]));
                        break;
                    default:
                        themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString(), Integer.parseInt(ptdong[0]));
                        break;
                }
            }
            fr.close();
            br.close();
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nhập vào sai định dạng", "Lỗi định dạng", 1);

        }
        return history;

    }

    public List<History> docFile(String duongdan) {
        FileReader fr = null;
        BufferedReader br = null;
        int bacdaoham = 1;
        Dathuc dathuc1, dathuc2, ketqua, du;
        dathuc1 = new Dathuc();
        dathuc2 = new Dathuc();
        ketqua = new Dathuc();
        du = new Dathuc();

        try {
            fr = new FileReader(duongdan);
            br = new BufferedReader(fr);

            String dong;
            String[] ptdong;
            while ((dong = br.readLine()) != null) {
                ptdong = dong.split("'");

                switch (Integer.parseInt(ptdong[0])) {
                    case 0:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.chiaDathuc(dathuc2)[0];

                        break;
                    case 1:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.nhandDathuc(dathuc2);
                        // code block
                        break;
                    case 2:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.CongDathuc(dathuc2);

                        // code block
                        break;
                    case 3:
                        dathuc1 = new Dathuc(ptdong[1]);
                        dathuc2 = new Dathuc(ptdong[2]);
                        ketqua = dathuc1.truDathuc(dathuc2);
                        // code block
                        break;
                    case 4:
                        dathuc1 = new Dathuc(ptdong[1]);
                        bacdaoham = Integer.parseInt(ptdong[2]);
                        ketqua = dathuc1.daohamDathuc(bacdaoham);
                        break;
                    case 5:
                        dathuc1 = new Dathuc(ptdong[1]);
                        x = Float.parseFloat(ptdong[2]);
                        ketqua = dathuc1.Tinhgiatri(x);
                        break;
                    default:
                        break;
                    // code block
                }
                switch (Integer.parseInt(ptdong[0])) {
                    case 0:
                        themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString() + "'" + du.toString(), Integer.parseInt(ptdong[0]));
                        break;
                    case 4:
                        themLichsu(dathuc1.toString(), Integer.toString(bacdaoham), ketqua.toString(), Integer.parseInt(ptdong[0]));
                        break;
                    default:
                        themLichsu(dathuc1.toString(), dathuc2.toString(), ketqua.toString(), Integer.parseInt(ptdong[0]));
                        break;
                }

            }
            fr.close();
            br.close();
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nhập vào sai định dạng", "Lỗi định dạng", 1);

        }
        return history;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App asd = new App();
                asd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btntinhgiatri;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnDaoham;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lbldathuc1;
    private javax.swing.JLabel lbldathuc2;
    private javax.swing.JTable tableLichsu;
    private javax.swing.JTextField txtDathuc1;
    private javax.swing.JTextField txtDathuc2;
    // End of variables declaration//GEN-END:variables

}
